modLoader="javafml"
loaderVersion="[37,)"
license="Apache License 2.0"

[[mods]] 
	modId="noitemdespawn" 
	version="2.0.7" 
	displayName="NoItemDespawn"
	description='''Items will no longer despawn, force-despawning works though'''
	authors="PT400C - Jomcraft Network"
	credits="Developed by Jomcraft Network"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/noitemdespawn"

[[dependencies.noitemdespawn]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.0,)"
    ordering="NONE"